front/urls.py
from django.conf.urls import patterns, include, url
from front import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^members/$', views.MemberView.as_view(), name='members'),
    url(r'^rules/$', views.RuleView.as_view(), name='rules'),
    url(r'^schedule/$', views.ScheduleView.as_view(), name='schedule'),
    url(r'^gallery/$', views.GalleryView.as_view(), name='gallery'),
    url(r'^stats/$', views.StatsView.as_view(), name='stats'),

    url(r'^charts/members_per_course/$', views.members_per_course, name='chart_members_by_course'),
    url(r'^charts/cakes_per_member/$', views.cakes_per_member, name='chart_cakes_per_member'),
)

kuchen/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', auth_views.login, {'template_name': 'front/login.html'}),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}),

    url(r'^robots.txt$', direct_to_template,
        {'template': 'front/robots.txt', 'mimetype': 'text/plain'}),

    url(r'', include('front.urls')),
)

# Static and media files
urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT, 'show_indexes': False,}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False,}),
)

front/models.py
# -*- coding: utf-8 -*-
from __future__ import print_function, division, absolute_import, unicode_literals

from datetime import date

from django.db import models
from django.contrib.auth import models as auth_models

from easy_thumbnails.fields import ThumbnailerImageField


# Managers

class CurrentSemesterManager(models.Manager):
    """A  manager that returns all assignments in the current semester."""

    def get_query_set(self):
        # Get current semester
        future_semesters = Semester.objects.filter(end_date__gte=date.today())
        semester = future_semesters.order_by('start_date')[0]
        # Filter assignments by semester
        return super(CurrentSemesterManager, self) \
                    .get_query_set() \
                    .filter(date__gte=semester.start_date, date__lte=semester.end_date)


class ActiveUsersManager(models.Manager):
    """A  manager that returns only active users."""

    def get_query_set(self):
        return super(ActiveUsersManager, self).get_query_set().filter(is_active=True)


# Models

class UserProfile(models.Model):
    COURSE_CHOICES = (
        ('B', 'Bauingenieurwesen'),
        ('E', 'Elektrotechnik'),
        ('EEU', 'Erneuerbare Energien'),
        ('I', 'Informatik'),
        ('L', 'Landschaftsarchitektur'),
        ('M', 'Maschinentechnik'),
        ('R', 'Raumplanung'),
    )
    user = models.OneToOneField(auth_models.User)
    course = models.CharField(u'Studiengang', max_length=3, choices=COURSE_CHOICES)
    phone = models.CharField(u'Natel', max_length=13, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Benutzerprofil'
        verbose_name_plural = 'Benutzerprofile'


class Assignment(models.Model):
    User = models.ForeignKey(auth_models.User)
    date = models.DateField(u'datum')
    unfulfilled = models.BooleanField(u'nicht erfüllt', default=False)
    photo = ThumbnailerImageField(u'foto', upload_to='photos', null=True, blank=True,
            help_text=u'Ein Beweisfoto des Kuchens.')

    objects = models.Manager()
    current_semester = CurrentSemesterManager()

    def __unicode__(self):
        return '%s: %s' % (self.date, self.User.username)

    class Meta:
        verbose_name = 'Termin'
        verbose_name_plural = 'Termine'
        unique_together = ('User', 'date')
        ordering = ['-date']


class Semester(models.Model):
    SEASON_CHOICES = (
        ('H', 'Herbstsemester'),
        ('F', 'Frühlingssemester'),
    )
    year = models.PositiveIntegerField(u'Jahr')
    season = models.CharField(u'Semester', max_length=1, choices=SEASON_CHOICES)
    start_date = models.DateField(u'Semesterbeginn')
    end_date = models.DateField(u'Semesterende')
    weekdays = models.CommaSeparatedIntegerField(u'Kuchentage', max_length=9, null=True, blank=True,
            help_text=u'Kommagetrennte Liste der Wochentage (1-5), an welchen es Kuchen gibt.')

    def weekday_list(self):
        return [int(day) for day in self.weekdays.split(',')]

    def assignments(self):
        return Assignment.objects.filter(date__lte=self.start_date, date__gte=self.start_date)

    def __unicode__(self):
        return '%ss %s' % (self.season, self.year)

    class Meta:
        verbose_name = 'Semester'
        verbose_name_plural = 'Semester'
        unique_together = ('year', 'season')
        ordering = ['start_date']


# User model functions

def name(self):
    """Return either full user first and last name or the username, if no
    further data is found."""
    if self.first_name or self.last_name:
        return ' '.join(filter(None, [self.first_name, self.last_name]))
    return self.username
auth_models.User.add_to_class('name', name)
auth_models.User.add_to_class('objects', models.Manager())
auth_models.User.add_to_class('active', ActiveUsersManager())

front/views.py
# -*- coding: utf-8 -*-
from __future__ import print_function, division, absolute_import, unicode_literals

import json
from datetime import date, datetime
from collections import defaultdict
from operator import itemgetter
from functools import wraps

from django.conf import settings
from django.http import HttpResponse, HttpResponseForbidden
from django.views.generic import TemplateView, ListView
from django.db.models import Count
from django.contrib.auth import models as auth_models

from lib.utils import daterange
from lib.mixins import LoginRequiredMixin

from front import models


class HomeView(TemplateView):
    template_name = 'front/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['switch'] = datetime.now().second % 2
        context['membercount'] = auth_models.User.active.count()
        return context


class MemberView(LoginRequiredMixin, ListView):
    template_name = 'front/members.html'
    queryset = auth_models.User.active.order_by('pk')


class RuleView(TemplateView):
    template_name = 'front/rules.html'


class ScheduleView(TemplateView):
    template_name = 'front/schedule.html'

    def get_context_data(self, **kwargs):
        context = super(ScheduleView, self).get_context_data(**kwargs)

        # Get current semester
        future_semesters = models.Semester.objects.filter(end_date__gte=date.today())
        semester = future_semesters.order_by('start_date')[0]

        # Get all possible dates in that semester
        context['semesters'] = []
        dates = daterange(semester.start_date, semester.end_date)
        context['semesters'].append((semester, dates))

        # Get all assignments, group by date
        assignments = defaultdict(list)
        for assignment in models.Assignment.objects.order_by('date', 'User__username'):
            assignments[assignment.date].append(assignment.User.name())
        context['assignments'] = assignments

        return context


class GalleryView(ListView):
    template_name = 'front/gallery.html'
    queryset = models.Assignment.objects \
                     .filter(photo__isnull=False).exclude(photo='') \
                     .order_by('-date')


class StatsView(TemplateView):
    template_name = 'front/stats.html'

    def get_context_data(self, **kwargs):
        context = super(StatsView, self).get_context_data(**kwargs)
        context['membercount'] = auth_models.User.active.count()
        return context


# JSON data views

def ajax_login_required(f):
    @wraps(f)
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden('Login required.')
        return f(request, *args, **kwargs)
    return wrapper


def handle_chart_json(request, data):
    if settings.DEBUG or request.is_ajax():
        return HttpResponse(json.dumps(data), content_type='application/json')
    return HttpResponseForbidden('Access via AJAX only.')


def members_per_course(request):
    """Return members per course for the current semester."""
    course_dict = dict(models.UserProfile.COURSE_CHOICES)
    data = list(models.UserProfile.objects.values('course')
                                  .filter(user__is_active=True)
                                  .annotate(mcount=Count('course'))
                                  .order_by('-mcount'))
    for course in data:
        course['course_full'] = course_dict[course['course']]
    return handle_chart_json(request, data)


@ajax_login_required
def cakes_per_member(request):
    """Return cakes per member for the current semester."""
    users = list(auth_models.User.active
                                 .values('id', 'first_name', 'last_name')
                                 .order_by('first_name'))

    query = models.Assignment.current_semester.filter(unfulfilled=False)
    aggregate = lambda qry: qry.values('User').annotate(ccount=Count('User')).order_by('-ccount')

    past = {a['User']: a['ccount'] for a in aggregate(query.filter(date__lte=date.today()))}
    future = {a['User']: a['ccount'] for a in aggregate(query.filter(date__gt=date.today()))}

    for user in users:
        user['past'] = past.get(user['id'], 0)
        user['future'] = future.get(user['id'], 0)
        del user['id']
    data = sorted(users, key=itemgetter('future'), reverse=True)
    data = sorted(data, key=itemgetter('past'), reverse=True)
    return handle_chart_json(request, data)

front/templates/front/base.html
<!doctype html>
<html lang="de">
{% load url from future %}
<head>
    <meta charset="utf-8">
    <title>{% block title %}Initiativkomitee für mehr Kuchen an der HSR{% endblock %}</title>
    <meta name="author" content="Initiativ- und Gründungskomitee der Kucheninitiative">

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block stylesheets %}
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Nobile|Lobster" type="text/css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
    {% endblock %}
</head>

<body class="{% block bodyclass %}{% endblock %}">
<div id="page">
    <div id="header">
        <a class="headertitlelink" href="{% url 'home' %}"><h1 class="headertitle">Kucheninitiative</h1></a>
        <ul id="nav">
            <li><a class="rules" href="{% url 'rules' %}">Regeln</a></li>
            <li><a class="schedule" href="{% url 'schedule' %}">Planung</a></li>
            <li><a class="gallery" href="{% url 'gallery' %}">Galerie</a></li>
            <li><a class="stats" href="{% url 'stats' %}">Statistiken</a></li>
            {% if not user.is_authenticated %}
            <li><a class="login" href="{% url 'django.contrib.auth.views.login' %}">Login</a></li>
            {% else %}
            <li><a class="members" href="{% url 'members' %}">Mitglieder</a></li>
            <li><a class="admin" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="logout" href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
            {% endif %}
        </ul>
        <div class="clear"></div>
    </div>
    <div id="main" class="hyphenate">
        {% block content %}{% endblock %}
    </div>
</div>

{% block scripts %}
    <script src="{{ STATIC_URL }}js/scripts.js"></script>
{% endblock scripts %}

</body>
</html>

front/templates/front/gallery.html
{% extends 'front/base.html' %}
{% load url from future %}
{% load thumbnail %}

{% block bodyclass %}gallery{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <!--[if lt IE 9]>
        <script type="text/javascript" src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <script src="{{ STATIC_URL }}js/fresco.js"></script>
{% endblock scripts %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/fresco.css">
{% endblock stylesheets %}

{% block content %}
    <h1>Galerie</h1>

    {% for assignment in object_list %}
        <a href="{{ assignment.photo.url }}"
            data-fresco-caption="Kuchen von {{ assignment.User.name }} am {{ assignment.date|date:"d.m.Y" }}"
            data-fresco-group="gallery"
            data-fresco-group-options="ui: 'inside', loop: true"
            data-fresco-type="image"
            class="fresco">
            <img src="{% thumbnail assignment.photo 252x185 crop %}" class="imageshadow"
                alt="Kuchen von {{ assignment.User.name }} am {{ assignment.date|date:"d.m.Y" }}"
                title="Kuchen von {{ assignment.User.name }} am {{ assignment.date|date:"d.m.Y" }}"
                width="252" height="185">
        </a>
    {% endfor %}
{% endblock %}

front/templates/front/home.html
{% extends 'front/base.html' %}
{% load url from future %}

{% block bodyclass %}home{% endblock %}

{% block content %}

<h1>Willkommen{% if user.is_authenticated and user.first_name %}, {{ user.first_name }}{% endif %}!</h1>

<p><strong>Die "Initiative für mehr Kuchen an der HSR" ist eine
solidarisch-gemeinschafliche Vereinigung zur Steigerung des allgemeinen
Wohlbefindens durch erhöhten und regelmässigen Kuchengenuss an der
Hochschule für Technik Rapperswil.</strong></p>

<p>Dies ist das digitale Zuhause dieser Vereinigung, sowie der zentrale Dreh-
und Angelpunkt, um die Initiative mit ihren inzwischen {{ membercount }}
Mitgliedern zu koordinieren.</p>

<p>Personen, welche die Initiative noch nicht kennen, oder auch Neumitglidern,
werden wärmstens die <a href="{% url 'rules' %}">Regeln</a> ans Herz
gelegt. Aktivmitglieder hingegen sollten regelmässig die
<a href="{% url 'schedule' %}">Kuchen-Termine</a> konsultieren.</p>

<p>Weitere Informationen finden sich in der <a href="{% url 'gallery' %}">
Galerie</a> und in den <a href="{% url 'stats' %}">Statistiken</a>.</p>

<p>Falls du Fragen hast oder der Initiative beitreten willst, sende eine Email
an {{ 'dbargen@hsr.ch'|urlize }}, {{ 'jfurrer@hsr.ch'|urlize }} und/oder
{{ 'cfaessle@hsr.ch'|urlize }}.</p>

{% endblock %}

front/templates/front/login.html
{% extends 'front/base.html' %}
{% load url from future %}

{% block bodyclass %}login{% endblock %}

{% block content %}

<h1>Login</h1>

{% if form.errors %}
    <p class="formerrors">Benutzername und/oder Passwort stimmen nicht. Versuch
    es bitte nochmals.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>

    <input id="submitbutton" type="submit" value="Login" />
    <input type="hidden" name="next" value="{{ next }}" />
    <br class="clear">
</form>
{% endblock %}

front/templates/front/members.html
{% extends 'front/base.html' %}
{% block bodyclass %}members{% endblock %}
{% block content %}
    <h1>Mitglieder</h1>

    <p>Die Mobiltelefon-Nummer wird hier lediglich publiziert, um die Person im
    WhatsApp identifizieren zu können. Für einen Eintrag in die WhatsApp-Gruppe
    melde man sich bei einem Mitglied das bereits der Gruppe zugehörig ist.</p>

    <table>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Studiengang</th>
            <th>Email</th>
            <th>Natel</th>
        </tr>
        {% for member in object_list %}
            <tr>
                <td>{{ member.pk }}</td>
                <td>{{ member.first_name }} {{ member.last_name }}</td>
                <td>{{ member.get_profile.get_course_display }}</td>
                <td>{{ member.email }}</td>
                <td>{{ member.get_profile.phone }}</td>
            </tr>
        {% endfor %}
    </table>

    <ul>
    </ul>
{% endblock %}

front/templates/front/rules.html
{% extends 'front/base.html' %}
{% block bodyclass %}rules{% endblock %}
{% block content %}
    <h1>Regelwerk</h1>

    <h2>Zweck</h2>

    <p>Die Initiative für mehr Kuchen an der HSR ist eine
    solidarisch-gemeinschafliche Vereinigung zur Steigerung des allgemeinen
    Wohlbefindens durch erhöhten und regelmässigen Kuchengenuss an der HSR.</p>

    <h2>Regeln</h2>

    <p>Jedes Mitglied ist verpflichet an den durch das Komitee bestimmten
    Terminen einen selbstgebackenen Kuchen an die HSR zu bringen. Der Kuchen
    steht dann allen Mitgliedern zum Verzehr zur Verfügung.</p>

    <p>Der Kuchen soll zu Zeiten und an Orten die möglichst vielen Mitgliedern
    den Genuss erlauben serviert werden. Üblicherweise ist dies die HSR
    Cafeteria in den Pausen. Ansonsten können die Mitglieder auch per HSR-Mail
    kontaktiert werden.</p>

    <p>Ziel eines jeden Mitgliedes sollte sein, die Qualität des vorigen
    Kuchens zu übertreffen.</p>

    <p>Jedes Mitglied darf neue Mitglieder anwerben in dem es potentiellen
    Neumitgliedern Kuchen anbietet, allerdings muss das potentielle Neumitglied
    zuvor über die Rechte und Pflichten aufgeklärt werden.</p>

    <p>Grundsätzlich soll Kuchen der für die Inititative gebacken wird auch nur
    von Mitgliedern gegessen werden, wer mitisst wird automatisch Mitglied,
    Ausnahmen von dieser Regel sollte es nur in den seltensten Fällen geben und
    müssen grundsätzlich mit dem Komitee besprochen werden.</p>

    <h2>Regelmissachtungen</h2>

    <p>Regelmissachtungen werden durch die Mitglieder geahndet und adäquat
    bestraft. Die einzige nicht erlaubte Strafe ist der Auschluss aus der
    Initiative.</p>

    <h2>Organe</h2>

    <p>Die Inititative für mehr Kuchen an der HSR besteht aus aus folgenden Organen:</p>
    <ul>
        <li>Initiativ- und Gründungskomitee (Danilo, Christian, Jonas)</li>
        <li>Aktivmitglieder (siehe Mitgliederliste)</li>
        <li>Kuchen</li>
    </ul>

    <h2>Beitritt</h2>

    <p>Es gibt zwei Möglichkeiten der Initiative beizutreten:</p>
    <ul>
        <li>Durch den Konsum von Kuchen, welcher von einem Initiativ-Mitglied
        gebacken wurde, wird man automatisch ein Aktivmitglied der Initiative
        und untersteht den zuvor genannten Regeln.</li>
        <li>Durch das Bekunden des Willens zum Beitritt beim Initiativkomitee
        wird man per sofort aktives Mitglied und untersteht den zuvor genannten
        Regeln.</li>
    </ul>

    <h2>Austritt</h2>

    <p>Austritt aus der Initiative kann nur durch Ableben des betreffenden
    Mitglieds oder durch den Austritt aus der HSR erfolgen.</p>

{% endblock %}

front/templates/front/schedule.html
{% extends 'front/base.html' %}
{% load lookup %}

{% block bodyclass %}schedule{% endblock %}

{% block content %}
    <h1>Kuchenplanung</h1>

    {% for semester, dates in semesters %}
        <h2>{{ semester.get_season_display }} {{ semester.year }}</h2>

        <table>

            <tr>
                <th>Datum</th>
                <th>Zuständige(r)</th>
            </tr>

            {% for date in dates %}

                {% ifchanged date.isocalendar.1 %}
                    <tr class="weekheader"><td colspan="2">Woche {{ date.isocalendar.1 }}</td></tr>
                {% endifchanged %}

                {% if date.isoweekday in semester.weekday_list %}
                    <tr class="weekday">
                        <td class="date">{{ date|date:"D, d.m." }}</td>
                        <td class="assigned">{% if assignments|lookup:date %}{{ assignments|lookup:date|join:", " }}{% endif %}</td>
                    </tr>
                {% endif %}

            {% endfor %}

        </table>

    {% endfor %}

{% endblock %}

front/templates/front/stats.html
{% extends 'front/base.html' %}
{% load url from future %}

{% block bodyclass %}stats{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}js/d3.v3.min.js"></script>
    <script src="{{ STATIC_URL }}js/d3.legend.js"></script>
    <script src="{{ STATIC_URL }}js/charts/members_per_course_pie.js"></script>
    {% if user.is_authenticated %}
        <script src="{{ STATIC_URL }}js/charts/cakes_per_member.js"></script>
    {% endif %}
{% endblock scripts %}

{% block content %}
    <h1>Statistiken</h1>

    <h2>Mitglieder pro Studiengang</h2>
    <p>Gesamtanzahl Mitglieder: {{ membercount }}.</p>
    <div id="members_per_course"></div>

    {% if not user.is_authenticated %}
        <h2>Weitere Statistiken</h2>
        <p>Um mehr Statistiken zu sehen, <a href="{% url 'django.contrib.auth.views.login' %}">logge dich bitte ein</a>.</p>
    {% else %}
        <h2>Kuchen pro Mitglied</h2>
        <p>Berücksichtigt werden alle Kuchen seit Semesterbeginn.</p>
        <div id="cakes_per_member"></div>
    {% endif %}

{% endblock %}